name: Node.js CI

on:
  push:
    branches: [ spa ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          path: client

      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: gingko/server
          path: server

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - run: echo $GITHUB_WORKSPACE

      - name: Copy client config.js file
        run: cp $HOME/client.config.js $GITHUB_WORKSPACE/client/config.js

      - name: Copy server config.js file
        run: cp $HOME/server.config.js $GITHUB_WORKSPACE/server/config.js

      - name: Install Test Server Dependencies
        run: cd ../server; npm i

      - name: Stop Test Server
        run: `pm2 stop --silent GingkoTest  || :`

      - name: Start Test Server
        run: PORT=8000 pm2 start ../server/index.js --name GingkoTest

      - run: npm i
      - run: npm run build --if-present

      - name: Cypress e2e Tests
        run: npx cypress run

      - name: Stop Test Server
        run: pm2 stop GingkoTest

      - name: Copy Build Files
        if: "!contains(github.event.head_commit.message, 'ci skip deploy')"
        run: cp -r $GITHUB_WORKSPACE/client/web/* $HOME/production/client/web

      - name: Restart Production Server
        if: "!contains(github.event.head_commit.message, 'ci skip deploy')"
        run: pm2 restart GingkoProduction