name: Node.js CI

on:
  push:
    branches: [ spa ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          path: client

      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: 'gingko/server'
          path: server

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Copy client config.js file
        run: cp $HOME/client.config.js ./config.js

      - name: Copy server config.js file
        run: cp $HOME/server.config.js ../server/config.js

      - run: npm i
      - run: npm run build --if-present

      - name: Cypress e2e Tests
        run: npx cypress run

      - name: Copy Build Files
        run: cp -r /web $HOME/production/client/web

      - name: Restart Server
        run: pm2 restart GingkoProduction