name: Node.js CI

on:
  push:
    branches: [ spa ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp $HOME/client.config.js ./config.js
      - run: npm i
      - run: npm run build --if-present
      - run: npx cypress run
      - run: cp -r /web $HOME/production/client/web
      - run: pm2 restart GingkoProduction